services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - my_mysql_data:/var/lib/mysql
    restart: if-stopped

  bot:
    build:
      context: ./bot
      dockerfile: dockerfile
    restart: if-stopped
    depends_on:
      - mysql

secrets:
  mysql_root_password:
    external: true
