from telegram import InlineKeyboardButton, InlineKeyboardMarkup, WebAppInfo

DATA: dict = {
    "start": {
        "keyboard": InlineKeyboardMarkup([[InlineKeyboardButton("🔗 Create New", callback_data="CQ_CREATE_NEW")], [InlineKeyboardButton("🗒 My Links", web_app=WebAppInfo("https://cnstrct.ru/p"))]]),
        "reply": "👋 Hello! Just press 'Create New' to create new short link or 'My Links' to list generated by you links"
    },
    "create_new": {
        "keyboard": InlineKeyboardMarkup([[InlineKeyboardButton("❌ Cancel", callback_data="CQ_CANCEL")]]),
        "reply": "Send URL that you want to shorten"
    }
}